import type { CheckoutEtiquetaProvider, EtiquetaOutcome, EtiquetaProviderInput } from '../types';

/**
 * Placeholder provider for the marketplace-owned carriers (Mercado Livre, Loja
 * Integrada, Amazon, Magalu, Shopee). Their labels are generated by the
 * marketplace and fetched through per-channel flows that don't exist yet
 * (Phase 5/6 — see the README table for the legacy per-carrier calls to port).
 *
 * Until then this reproduces the legacy `'unsupported'` reject as a friendly
 * toast + a typed outcome, rather than the wrong thing (routing a marketplace
 * pedido through the generic PDF, which would print a store label for a
 * carrier that already has its own).
 */
export const unsupportedMarketplaceProvider: CheckoutEtiquetaProvider = {
  tipos: ['mercadoLivre', 'lojaIntegrada', 'amz', 'magalu', 'shopee'],

  async emitirOuImprimir(input: EtiquetaProviderInput): Promise<EtiquetaOutcome> {
    input.ui.notify({
      title: 'Etiqueta',
      message: 'Emissão de etiqueta para esta transportadora ainda não suportada.',
      color: 'yellow',
    });
    return {
      status: 'unsupported',
      reason: `Etiqueta para "${input.intFrete.tipo}" ainda não suportada.`,
    };
  },
};
