import type { CheckoutEtiquetaProvider, EtiquetaOutcome, EtiquetaProviderInput } from '../types';

/**
 * Placeholder provider for the marketplace-owned carriers still without a
 * fetch flow (Loja Integrada, Amazon, Magalu — Mercado Livre and Shopee have
 * graduated to `providers/mercadoLivre.ts` and `providers/shopee.ts`). Their
 * labels are generated by the marketplace and fetched through per-channel flows
 * that don't exist yet (Phase 5/6 — see the README table for the legacy
 * per-carrier calls to port).
 *
 * Until then this reproduces the legacy `'unsupported'` reject as a friendly
 * toast + a typed outcome, rather than the wrong thing (routing a marketplace
 * pedido through the generic PDF, which would print a store label for a
 * carrier that already has its own).
 *
 * ⚠️ A tipo leaves this list in the SAME change that registers its provider and
 * flips its `FREIGHT_TIPO_CAPS.canFetchLabel`: the registry throws at load on a
 * tipo claimed twice, and `registry.test.ts`'s drift guard reds either half
 * alone.
 */
export const unsupportedMarketplaceProvider: CheckoutEtiquetaProvider = {
  tipos: ['lojaIntegrada', 'amz', 'magalu'],

  async emitirOuImprimir(input: EtiquetaProviderInput): Promise<EtiquetaOutcome> {
    input.ui.notify({
      title: 'Etiqueta',
      message: 'Emissão de etiqueta para esta transportadora ainda não suportada.',
      color: 'yellow',
    });
    return {
      status: 'unsupported',
      reason: `Etiqueta para "${input.intFrete.tipo}" ainda não suportada.`,
    };
  },
};
