/**
 * The committed shape document, `__wire__/SHAPES.txt`.
 *
 * ⚠️ It exists so a fixture refresh is **reviewable**. A re-promoted corpus is
 * thousands of changed JSON lines that no human reads line by line; the same
 * change here is a handful of `path: type` lines, and a field rename shows up as
 * one `-` beside one `+` — which is exactly the drift this whole corpus was
 * committed to catch.
 *
 * Per-file digests were considered and rejected: 32 more files, every one able
 * to drift from the body it describes. One aggregate document plus
 * `wireShapes.test.ts` regenerating and comparing it cannot go stale.
 *
 * ⚠️ **This lives in `lib/`, not in the script, on purpose.**
 * `scripts/promote-fixtures.ts` calls `main()` at module scope, so a test
 * importing the renderer from there would run a real promote as an import side
 * effect. An `import.meta.main`-style guard is not a reliable fix on Windows.
 */
import type { WireValue } from './redact';
import { wireDigest } from './wireDigest';
import { listWireFixtures, readWireFixture } from './wireCorpus';

export const SHAPES_FILE = 'SHAPES.txt';

const CABECALHO: readonly string[] = [
  '# Structural shapes of the __wire__ corpus',
  '#',
  '# Generated by `pnpm --filter @delfrance/mercado-livre-app promote:fixtures`.',
  '# One `path: type` line per leaf; `null` is its own type, `[]` is an empty',
  '# array, and types union across occurrences. Review THIS diff, not the JSON.',
  '',
];

/** Render the document from already-parsed bodies, keyed by filename. */
export function renderShapesDocument(bodies: ReadonlyMap<string, WireValue>): string {
  const secoes = [...bodies.keys()]
    .sort()
    .map((file) => `## ${file}\n${wireDigest(bodies.get(file) as WireValue)}`);
  return [...CABECALHO, ...secoes, ''].join('\n');
}

/** Render it from the committed corpus on disk — what the test compares against. */
export function renderShapesFromCorpus(): string {
  const bodies = new Map<string, WireValue>();
  for (const file of listWireFixtures()) bodies.set(file, readWireFixture(file));
  return renderShapesDocument(bodies);
}
