import { emitRules } from './emit';
import { DOMAINS, EXTRA_MATCH_BLOCKS, VALIDATOR_WHITELIST } from './registry';

const HEADER = `// GENERATED by @delfrance/rules-gen — DO NOT EDIT.
// Regenerate: pnpm --filter @delfrance/rules-gen gen:rules
//
// Deploy stays manual/coordinated (CLAUDE.md critical rule 1): production
// still runs the Flutter-generated ruleset, and the staging e2e namespaces
// (e2e_<runId>_*) are not covered by these fixed paths.
`;

/** Pure + deterministic — same inputs, byte-identical output. */
export function generateRulesSource(): string {
  return `${HEADER}\n${emitRules(DOMAINS, EXTRA_MATCH_BLOCKS, VALIDATOR_WHITELIST)}`;
}
