import { emitRules } from './emit';
import { DOMAINS, E2E_NAMESPACE_BLOCK, EXTRA_MATCH_BLOCKS, VALIDATOR_WHITELIST } from './registry';

const HEADER = `// GENERATED by @delfrance/rules-gen — DO NOT EDIT.
// Regenerate: pnpm --filter @delfrance/rules-gen gen:rules
//
// Deploy stays manual/coordinated (CLAUDE.md critical rule 1). PRODUCTION runs
// this file; the STAGING project runs the --e2e variant (firestore.e2e.rules
// via firebase.staging.json), which adds the e2e_<runId>_* namespace block so
// Playwright fixtures aren't default-denied. These fixed paths do not cover
// those namespaces — that is intentional for production.
`;

const E2E_HEADER = `// GENERATED by @delfrance/rules-gen (--e2e) — DO NOT EDIT.
// Regenerate: pnpm --filter @delfrance/rules-gen gen:rules:e2e
//
// STAGING-ONLY variant: byte-identical to firestore.rules plus one match block
// granting the authenticated e2e test user access to the run-scoped
// e2e_<runId>_* namespaces. Deploy ONLY to staging (firebase.staging.json).
// NEVER deploy this to production — it opens every e2e_-prefixed collection.
`;

/** Pure + deterministic — same inputs, byte-identical output. */
export function generateRulesSource(opts: { e2e?: boolean } = {}): string {
  const header = opts.e2e ? E2E_HEADER : HEADER;
  const extraBlocks = opts.e2e ? [...EXTRA_MATCH_BLOCKS, E2E_NAMESPACE_BLOCK] : EXTRA_MATCH_BLOCKS;
  return `${header}\n${emitRules(DOMAINS, extraBlocks, VALIDATOR_WHITELIST)}`;
}
