/* GENERATED by tools/cmun-table. DO NOT EDIT — see the refresh runbook in
 * tools/cmun-table/README.md.
 *
 * ⚠️ PLACEHOLDER — NOT YET VENDORED. ⚠️
 *
 * `rangeCount: 0` makes every `lookupCodigoMunicipio` return `null`, so the
 * resolver falls straight through to ViaCEP — i.e. exactly the behaviour that
 * shipped before #785. The placeholder degrades to today's production
 * behaviour rather than to a silently wrong município, which is why it is safe
 * to have on a branch.
 *
 * The data lives ONLY in the production Firestore `CMUN` collection (there is
 * no CSV, JSON or seed file anywhere in `.old/`). To fill this in:
 *
 *   1. pnpm --filter @delfrance/cmun-table dump -- --project <prod-project-id>
 *   2. pnpm --filter @delfrance/cmun-table vendor
 *
 * Step 1 needs production credentials, so it is a human step.
 */
import type { EncodedCMunTable } from './codec';

export const CMUN_RANGES: EncodedCMunTable = {
  rangeCount: 0,
  startGaps: '',
  rangeLens: '',
  codes: '',
};

export interface CMunTableProvenance {
  /** Where the rows came from. */
  readonly source: string;
  /** ISO date of the production export, or `null` while unvendored. */
  readonly exportedAt: string | null;
  /** The committed dump this table was built from, repo-relative. */
  readonly dumpFile: string | null;
  /** sha256 of that dump, so a re-vendor can prove it used the same input. */
  readonly dumpSha256: string | null;
  /** Distinct 7-digit cMun codes represented. */
  readonly codeCount: number;
}

export const CMUN_TABLE_PROVENANCE: CMunTableProvenance = {
  source: 'PLACEHOLDER — run tools/cmun-table dump + vendor',
  exportedAt: null,
  dumpFile: null,
  dumpSha256: null,
  codeCount: 0,
};
