/**
 * Anexo III (NT 2025.002) — the CST IBS/CBS table and the NF-e rows of the
 * cClassTrib table, with their indicators. HAND-TRANSCRIBED DATA, not codegen
 * output (root CLAUDE.md rule 3): a one-off script read the public SVRS
 * "Conformidade Fácil" page and the result is committed and reviewed as source.
 *
 * Source: https://dfe-portal.svrs.rs.gov.br/DFE/ClassificacaoTributaria — the
 * JSON literal the page renders its table (and its CSV/Excel/JSON exports)
 * from. Retrieved 2026-09-28; latest row publication on the page 2026-06-22.
 *
 * Filter: rows whose DF-e list includes NF-e (`IndNfe`) — the only document this
 * ERP emits. 97 of the 164 rows. CSTs with NO NF-e row: '010', '011', '220', '221', '222', '400', '820'.
 *
 * Folds applied (presentation only): descriptions are the page's "Descrição
 * Reduzida" with CR/LF turned into spaces, runs of spaces collapsed and ends
 * trimmed. Codes, indicators, rates and dates are verbatim.
 *
 * Refresh: `.claude/skills/nfe/references/sources/nt/2025/cClassTrib-CST-tables-SOURCE.md`.
 * A stale copy only ever WARNS — emission is checked against the structural
 * rule alone (`cstClassTribStructurallyValid`), never table membership.
 */
import type { CClassTribEntry, CstIbsCbsEntry, ProvenienciaTabelaRtc } from './cclasstrib';

export const CCLASSTRIB_PROVENIENCIA: ProvenienciaTabelaRtc = {
  fonte: 'https://dfe-portal.svrs.rs.gov.br/DFE/ClassificacaoTributaria',
  obtidoEm: '2026-09-28',
  publicadoAte: '2026-06-22',
  filtro: 'DF-e inclui NF-e (IndNfe)',
  linhas: 97,
};

/** The 18 CSTs (all of them — the CST list is not filtered by DF-e). */
export const CST_IBSCBS_TABELA: readonly CstIbsCbsEntry[] = [
  { cst: '000', descricao: 'Tributação integral', ind: ['exigeTributacao'] },
  { cst: '010', descricao: 'Tributação com alíquotas uniformes', ind: ['exigeTributacao'] },
  {
    cst: '011',
    descricao: 'Tributação com alíquotas uniformes reduzidas',
    ind: ['exigeTributacao', 'reducaoAliquota'],
  },
  { cst: '200', descricao: 'Alíquota reduzida', ind: ['exigeTributacao', 'reducaoAliquota'] },
  { cst: '220', descricao: 'Alíquota fixa', ind: ['exigeTributacao'] },
  { cst: '221', descricao: 'Alíquota fixa proporcional', ind: ['exigeTributacao'] },
  { cst: '222', descricao: 'Redução de Base de Cálculo', ind: ['exigeTributacao', 'reducaoBC'] },
  { cst: '400', descricao: 'Isenção', ind: [] },
  { cst: '410', descricao: 'Imunidade e não incidência', ind: [] },
  { cst: '510', descricao: 'Diferimento', ind: ['exigeTributacao', 'diferimento'] },
  {
    cst: '515',
    descricao: 'Diferimento com redução de alíquota',
    ind: ['exigeTributacao', 'reducaoAliquota', 'diferimento'],
  },
  { cst: '550', descricao: 'Suspensão', ind: ['exigeTributacao'] },
  { cst: '620', descricao: 'Tributação Monofásica', ind: ['monofasica'] },
  { cst: '800', descricao: 'Transferência de crédito', ind: ['transferenciaCredito'] },
  { cst: '810', descricao: 'Ajuste de IBS na ZFM', ind: ['credPresIbsZfm'] },
  { cst: '811', descricao: 'Ajustes', ind: ['ajusteCompetencia'] },
  { cst: '820', descricao: 'Tributação em documento específico', ind: [] },
  { cst: '830', descricao: 'Exclusão da Base de Cálculo', ind: ['exigeTributacao'] },
];

/** cClassTrib rows valid for NF-e, sorted ascending by code. */
export const CCLASSTRIB_TABELA: readonly CClassTribEntry[] = [
  {
    cClassTrib: '000001',
    cst: '000',
    descricao: 'Situações tributadas integralmente pelo IBS e CBS.',
    tipoAliquota: 2,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '000003',
    cst: '000',
    descricao: 'Regime automotivo - projetos incentivados (art. 311)',
    tipoAliquota: 2,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['credPresOper'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '000004',
    cst: '000',
    descricao: 'Regime automotivo - projetos incentivados (art. 312)',
    tipoAliquota: 2,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['credPresOper'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '000005',
    cst: '000',
    descricao:
      'Operação com EAC destinado à mistura com gasolina A, mas com saída do biocombustível com destinação diversa',
    tipoAliquota: 2,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2026-01-01',
  },
  {
    cClassTrib: '200002',
    cst: '200',
    descricao: 'Fornecimento ou importação para produtor rural não contribuinte ou TAC',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200003',
    cst: '200',
    descricao: 'Vendas de produtos destinados à alimentação humana (Anexo I)',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200004',
    cst: '200',
    descricao: 'Fornecimento de dispositivos médicos (Anexo XII)',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200005',
    cst: '200',
    descricao:
      'Fornecimento de dispositivos médicos para órgãos da administração pública e entidades de saúde imunes (Anexo IV)',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200006',
    cst: '200',
    descricao: 'Situação de emergência de saúde pública reconhecida pelo Poder público',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200007',
    cst: '200',
    descricao:
      'Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência (Anexo XIII)',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200008',
    cst: '200',
    descricao:
      'Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência adquiridos por órgãos da administração pública (Anexo V)',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200009',
    cst: '200',
    descricao: 'Fornecimento dos medicamentos registrados na Anvisa',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200010',
    cst: '200',
    descricao:
      'Fornecimento dos medicamentos registrados na Anvisa, adquiridos por órgãos da administração pública',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200011',
    cst: '200',
    descricao:
      'Fornecimento das composições para nutrição enteral e parenteral quando adquiridas por órgãos da administração pública (Anexo VI)',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200012',
    cst: '200',
    descricao: 'Situação de emergência de saúde pública reconhecida pelo Poder público',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200013',
    cst: '200',
    descricao: 'Fornecimento de tampões higiênicos, absorventes higiênicos internos ou externos',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200014',
    cst: '200',
    descricao: 'Fornecimento dos produtos hortícolas, frutas e ovos (Anexo XV)',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200015',
    cst: '200',
    descricao:
      'Venda de automóveis de passageiros de fabricação nacional adquiridos por motoristas profissionais ou pessoas com deficiência',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200020',
    cst: '200',
    descricao:
      'Operação praticada por sociedades cooperativas optantes por regime específico do IBS e CBS',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200022',
    cst: '200',
    descricao:
      'Operação originada fora da ZFM que destine bem material industrializado a contribuinte estabelecido na ZFM',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200023',
    cst: '200',
    descricao:
      'Operação realizada por indústria incentivada que destine bem material intermediário para outra indústria incentivada na ZFM',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200024',
    cst: '200',
    descricao:
      'Operação originada fora das Áreas de Livre Comércio destinadas a contribuinte estabelecido nas Áreas de Livre Comércio',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200030',
    cst: '200',
    descricao: 'Venda dos dispositivos médicos (Anexo IV)',
    tipoAliquota: 2,
    pRedIBS: 60,
    pRedCBS: 60,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200031',
    cst: '200',
    descricao:
      'Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência (Anexo V)',
    tipoAliquota: 2,
    pRedIBS: 60,
    pRedCBS: 60,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200032',
    cst: '200',
    descricao:
      'Fornecimento dos medicamentos registrados na Anvisa ou produzidos por farmácias de manipulação, ressalvados os medicamentos sujeitos à alíquota zero',
    tipoAliquota: 2,
    pRedIBS: 60,
    pRedCBS: 60,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200033',
    cst: '200',
    descricao: 'Fornecimento das composições para nutrição enteral e parenteral (Anexo VI)',
    tipoAliquota: 2,
    pRedIBS: 60,
    pRedCBS: 60,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200034',
    cst: '200',
    descricao: 'Fornecimento dos alimentos destinados ao consumo humano (Anexo VII)',
    tipoAliquota: 2,
    pRedIBS: 60,
    pRedCBS: 60,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200035',
    cst: '200',
    descricao: 'Fornecimento dos produtos de higiene pessoal e limpeza (Anexo VIII)',
    tipoAliquota: 2,
    pRedIBS: 60,
    pRedCBS: 60,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200036',
    cst: '200',
    descricao:
      'Fornecimento de produtos agropecuários, aquícolas, pesqueiros, florestais e extrativistas vegetais in natura',
    tipoAliquota: 2,
    pRedIBS: 60,
    pRedCBS: 60,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200038',
    cst: '200',
    descricao: 'Fornecimento dos insumos agropecuários e aquícolas (Anexo IX)',
    tipoAliquota: 2,
    pRedIBS: 60,
    pRedCBS: 60,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200039',
    cst: '200',
    descricao:
      'Fornecimento dos bens e serviços relacionados com produções nacionais artísticas, culturais, de eventos, jornalísticas e audiovisuais (Anexo X)',
    tipoAliquota: 2,
    pRedIBS: 60,
    pRedCBS: 60,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200043',
    cst: '200',
    descricao:
      'Fornecimento à administração pública dos serviços e dos bens relativos à soberania (Anexo XI)',
    tipoAliquota: 2,
    pRedIBS: 60,
    pRedCBS: 60,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200047',
    cst: '200',
    descricao: 'Bares e Restaurantes',
    tipoAliquota: 2,
    pRedIBS: 40,
    pRedCBS: 40,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '200053',
    cst: '200',
    descricao:
      'Fornecimento de medicamentos registrados na Anvisa, quando classificados como soros ou vacinas',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: [],
    inicioVigencia: '2026-01-01',
  },
  {
    cClassTrib: '200054',
    cst: '200',
    descricao:
      'Fornecimento de bem material pela cooperativa de produção agropecuária a associado não sujeito ao regime regular do IBS e da CBS',
    tipoAliquota: 2,
    pRedIBS: 100,
    pRedCBS: 100,
    ind: ['estornoCred'],
    inicioVigencia: '2026-01-01',
  },
  {
    cClassTrib: '410001',
    cst: '410',
    descricao:
      'Fornecimento de bonificações quando constem no documento fiscal e que não dependam de evento posterior',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410002',
    cst: '410',
    descricao: 'Transferências entre estabelecimentos pertencentes ao mesmo contribuinte',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410003',
    cst: '410',
    descricao: 'Doações sem contraprestação em benefício do doador',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410004',
    cst: '410',
    descricao: 'Exportações de bens e serviços',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410005',
    cst: '410',
    descricao:
      'Fornecimentos realizados pela União, pelos Estados, pelo Distrito Federal e pelos Municípios',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410006',
    cst: '410',
    descricao: 'Fornecimentos realizados por entidades religiosas e templos de qualquer culto',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410007',
    cst: '410',
    descricao:
      'Fornecimentos realizados por partidos políticos, entidades sindicais e instituições de educação e de assistência social',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410008',
    cst: '410',
    descricao: 'Fornecimentos de livros, jornais, periódicos e do papel destinado a sua impressão',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410009',
    cst: '410',
    descricao: 'Fornecimentos de fonogramas e videofonogramas musicais produzidos no Brasil',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410012',
    cst: '410',
    descricao: 'Fornecimento de condomínio edilício não optante pelo regime regular',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410013',
    cst: '410',
    descricao: 'Exportações de combustíveis',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410014',
    cst: '410',
    descricao: 'Fornecimento de produtor rural não contribuinte',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['credPresOper'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410016',
    cst: '410',
    descricao: 'Fornecimento ou aquisição de resíduos sólidos',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['credPresOper'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410017',
    cst: '410',
    descricao: 'Aquisição de bem móvel com crédito presumido sob condição de revenda realizada',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410019',
    cst: '410',
    descricao: 'Exclusão da gorjeta na base de cálculo no fornecimento de alimentação',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410020',
    cst: '410',
    descricao:
      'Exclusão do valor de intermediação na base de cálculo no fornecimento de alimentação',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '410026',
    cst: '410',
    descricao: 'Doação com anulação de crédito',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['estornoCred'],
    inicioVigencia: '2025-09-30',
  },
  {
    cClassTrib: '410027',
    cst: '410',
    descricao: 'Exportação de serviço ou de bem imaterial',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-11-19',
  },
  {
    cClassTrib: '410029',
    cst: '410',
    descricao: 'Operações acobertadas somente pelo ICMS',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-11-19',
  },
  {
    cClassTrib: '410030',
    cst: '410',
    descricao: 'Estorno de crédito por perecimento, deteriorização, roubo, furto ou extravio.',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['estornoCred'],
    inicioVigencia: '2025-11-19',
  },
  {
    cClassTrib: '410031',
    cst: '410',
    descricao: 'Fornecimento em período anterior ao início de vigência de incidências de CBS e IBS',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-11-19',
  },
  {
    cClassTrib: '410035',
    cst: '410',
    descricao: 'Fornecimento realizado por nanoempreendedor',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2026-01-01',
  },
  {
    cClassTrib: '410999',
    cst: '410',
    descricao: 'Operações não onerosas sem previsão de tributação, não especificadas anteriormente',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '510001',
    cst: '510',
    descricao:
      'Operações, sujeitas a diferimento, com energia elétrica, relativas à importação, geração, comercialização, distribuição e transmissão',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '515001',
    cst: '515',
    descricao:
      'Operações, sujeitas a diferimento, com insumos agropecuários e aquícolas (Anexo IX)',
    tipoAliquota: 2,
    pRedIBS: 60,
    pRedCBS: 60,
    ind: [],
    inicioVigencia: '2025-09-30',
  },
  {
    cClassTrib: '550001',
    cst: '550',
    descricao: 'Exportações de bens materiais',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550002',
    cst: '550',
    descricao: 'Regime de Trânsito',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550003',
    cst: '550',
    descricao: 'Regimes de Depósito (art. 85)',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550004',
    cst: '550',
    descricao: 'Regimes de Depósito (art. 87)',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550005',
    cst: '550',
    descricao: 'Regimes de Depósito (art. 87, Parágrafo único)',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550006',
    cst: '550',
    descricao: 'Regimes de Permanência Temporária',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550007',
    cst: '550',
    descricao: 'Regimes de Aperfeiçoamento',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550008',
    cst: '550',
    descricao: 'Importação de bens para o Regime de Repetro-Temporário',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550009',
    cst: '550',
    descricao: 'GNL-Temporário',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550010',
    cst: '550',
    descricao: 'Repetro-Permanente',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550011',
    cst: '550',
    descricao: 'Repetro-Industrialização',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550012',
    cst: '550',
    descricao: 'Repetro-Nacional',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550013',
    cst: '550',
    descricao: 'Repetro-Entreposto',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550014',
    cst: '550',
    descricao: 'Zona de Processamento de Exportação',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550015',
    cst: '550',
    descricao:
      'Regime Tributário para Incentivo à Modernização e à Ampliação da Estrutura Portuária',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550016',
    cst: '550',
    descricao: 'Regime Especial de Incentivos para o Desenvolvimento da Infraestrutura',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550017',
    cst: '550',
    descricao: 'Regime Tributário para Incentivo à Atividade Econômica Naval',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550018',
    cst: '550',
    descricao: 'Desoneração da aquisição de bens de capital',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550019',
    cst: '550',
    descricao: 'Importação de bem material por indústria incentivada para utilização na ZFM',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550020',
    cst: '550',
    descricao: 'Áreas de livre comércio',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '550021',
    cst: '550',
    descricao: 'Industrialização destinada a exportações',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2025-09-30',
  },
  {
    cClassTrib: '550022',
    cst: '550',
    descricao:
      'Regime Especial de Incentivos para a Produção de Hidrogênio de Baixa Emissão de Carbono (Rehidro)',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2026-01-01',
  },
  {
    cClassTrib: '550023',
    cst: '550',
    descricao:
      'Operações com hidrocarbonetos líquidos derivados de petróleo não combustíveis ou de gás natural, inclusive nafta',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['tribRegular'],
    inicioVigencia: '2026-01-01',
  },
  {
    cClassTrib: '620001',
    cst: '620',
    descricao: 'Tributação monofásica sobre combustíveis',
    tipoAliquota: 2,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['monoPadrao'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '620002',
    cst: '620',
    descricao: 'Tributação monofásica com responsabilidade pela retenção sobre combustíveis',
    tipoAliquota: 2,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['monoPadrao', 'monoRetencao'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '620003',
    cst: '620',
    descricao: 'Tributação monofásica com responsabilidade de retenção de tributos por terceiros',
    tipoAliquota: 2,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['monoDiferimento'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '620004',
    cst: '620',
    descricao:
      'Tributação monofásica sobre mistura de EAC com gasolina A em percentual superior ao obrigatório',
    tipoAliquota: 2,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['monoRetido', 'pBioDiferenca'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '620005',
    cst: '620',
    descricao:
      'Tributação monofásica sobre mistura de EAC com gasolina A em percentual inferior ao obrigatório',
    tipoAliquota: 2,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['monoRetido', 'pBioDiferenca'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '620006',
    cst: '620',
    descricao: 'Tributação monofásica sobre combustíveis cobrada anteriormente',
    tipoAliquota: 2,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: ['monoRetido'],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '620007',
    cst: '620',
    descricao: 'Perecimento, deteriorização, roubo, furto ou extravio no regime monofásico',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2026-01-01',
  },
  {
    cClassTrib: '800001',
    cst: '800',
    descricao: 'Fusão, cisão ou incorporação',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '800002',
    cst: '800',
    descricao: 'Transferência de crédito do associado, inclusive as cooperativas singulares',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '810001',
    cst: '810',
    descricao: 'Crédito presumido sobre o valor apurado nos fornecimentos a partir da ZFM',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
  {
    cClassTrib: '811001',
    cst: '811',
    descricao: 'Anulação de Crédito por Saídas Imunes/Isentas',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-09-30',
  },
  {
    cClassTrib: '811002',
    cst: '811',
    descricao: 'Débitos de notas fiscais não processadas na apuração',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-09-30',
  },
  {
    cClassTrib: '811003',
    cst: '811',
    descricao: 'Desenquadramento do Simples Nacional',
    tipoAliquota: 3,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-09-30',
  },
  {
    cClassTrib: '830001',
    cst: '830',
    descricao:
      'Documento com exclusão da BC da CBS e do IBS de energia elétrica fornecida pela distribuidora à UC',
    tipoAliquota: 2,
    pRedIBS: 0,
    pRedCBS: 0,
    ind: [],
    inicioVigencia: '2025-05-05',
  },
];
