import { type EncodedCMunTable, decodeCMunTable, encodeCMunTable } from './deps';
import {
  type CmunDumpRow,
  type ValidateResult,
  type ValidateOptions,
  validateDump,
} from './validate';

/**
 * The pure half of the vendoring: dump rows in, `ranges.data.ts` source out.
 *
 * Split from `vendor.ts` (the IO shell) purely so it can be tested — a bug in
 * the module template would otherwise only surface when someone imports the
 * generated file.
 */

export interface RenderMeta {
  /** Repo-relative path of the dump, for the provenance header. */
  readonly dumpFile: string;
  readonly dumpSha256: string;
  /** ISO date (YYYY-MM-DD). */
  readonly exportedAt: string;
}

export interface RenderResult {
  readonly source: string;
  readonly encoded: EncodedCMunTable;
  readonly validation: ValidateResult;
}

function renderSource(encoded: EncodedCMunTable, codeCount: number, meta: RenderMeta): string {
  return `/* GENERATED by tools/cmun-table. DO NOT EDIT — see the refresh runbook in
 * tools/cmun-table/README.md.
 *
 * Source:      Firestore collection \`CMUN\` (projeto de produção) — the legacy
 *              Flutter \`TabelaoCmun\`, which is the ONLY copy of this dataset.
 * Exported:    ${meta.exportedAt}
 * Dump:        ${meta.dumpFile}
 * Dump sha256: ${meta.dumpSha256}
 * Rows:        ${encoded.rangeCount} faixas, ${codeCount} municípios
 *
 * Regenerate:  pnpm --filter @delfrance/cmun-table vendor
 *
 * Encoding: three comma-separated base36 integer lists, decoded lazily into
 * \`Uint32Array\`s on first lookup. \`startGaps\` stores each faixa's start as a
 * NON-NEGATIVE gap from the previous faixa's end, which makes overlapping
 * faixas structurally unrepresentable. See ./codec.ts.
 */
import type { EncodedCMunTable } from './codec';

export const CMUN_RANGES: EncodedCMunTable = {
  rangeCount: ${encoded.rangeCount},
  startGaps:
    '${encoded.startGaps}',
  rangeLens:
    '${encoded.rangeLens}',
  codes:
    '${encoded.codes}',
};

export interface CMunTableProvenance {
  /** Where the rows came from. */
  readonly source: string;
  /** ISO date of the production export, or \`null\` while unvendored. */
  readonly exportedAt: string | null;
  /** The committed dump this table was built from, repo-relative. */
  readonly dumpFile: string | null;
  /** sha256 of that dump, so a re-vendor can prove it used the same input. */
  readonly dumpSha256: string | null;
  /** Distinct 7-digit cMun codes represented. */
  readonly codeCount: number;
}

export const CMUN_TABLE_PROVENANCE: CMunTableProvenance = {
  source: 'Firestore CMUN (produção) — legacy TabelaoCmun',
  exportedAt: '${meta.exportedAt}',
  dumpFile: '${meta.dumpFile}',
  dumpSha256: '${meta.dumpSha256}',
  codeCount: ${codeCount},
};
`;
}

/**
 * Validate → encode → round-trip → render.
 *
 * The round-trip runs the encoded columns back through the RUNTIME decoder
 * (`@delfrance/core`'s, via `deps.ts`) and compares every triple against the
 * input. That is what makes an encoder/decoder drift impossible: a mismatch
 * throws before anything is written.
 */
export function renderRangesModule(
  rows: readonly CmunDumpRow[],
  meta: RenderMeta,
  options: ValidateOptions = {},
): RenderResult {
  const validation = validateDump(rows, options);
  const encoded = encodeCMunTable(validation.ranges);

  const decoded = decodeCMunTable(encoded);
  validation.ranges.forEach((range, i) => {
    if (
      decoded.starts[i] !== range.cepInicial ||
      decoded.ends[i] !== range.cepFinal ||
      decoded.codes[i] !== range.cMun
    ) {
      throw new Error(
        `Round-trip falhou na faixa ${i}: esperado ` +
          `${range.cepInicial}-${range.cepFinal}/${range.cMun}, decodificado ` +
          `${String(decoded.starts[i])}-${String(decoded.ends[i])}/${String(decoded.codes[i])}`,
      );
    }
  });

  return {
    source: renderSource(encoded, validation.codeCount, meta),
    encoded,
    validation,
  };
}
