import { describe, expect, it } from 'vitest';
import { decodeCMunTable } from './deps';
import { renderRangesModule } from './render';
import type { CmunDumpRow } from './validate';

const META = {
  dumpFile: 'tools/cmun-table/data/cmun-export-2026-08-04.jsonl',
  dumpSha256: 'a'.repeat(64),
  exportedAt: '2026-08-04',
} as const;

const OPTS = { sanityBands: false } as const;

const ROWS: readonly CmunDumpRow[] = [
  {
    cepInicial: 1_000_000,
    cepFinal: 1_099_999,
    cMun: '3550308',
    nomeMunicipio: 'SAO PAULO',
    uf: 'SP',
  },
  {
    cepInicial: 1_100_000,
    cepFinal: 1_199_999,
    cMun: '3550308',
    nomeMunicipio: 'SAO PAULO',
    uf: 'SP',
  },
  {
    cepInicial: 2_000_000,
    cepFinal: 2_099_999,
    cMun: '3304557',
    nomeMunicipio: 'RIO DE JANEIRO',
    uf: 'RJ',
  },
  {
    cepInicial: 7_000_000,
    cepFinal: 7_299_999,
    cMun: '5300108',
    nomeMunicipio: 'BRASILIA',
    uf: 'DF',
  },
];

/** Pull the three encoded columns back out of the rendered module source. */
function extractColumns(source: string) {
  const rangeCount = Number(/rangeCount: (\d+),/.exec(source)?.[1]);
  const [startGaps, rangeLens, codes] = [...source.matchAll(/^ {4}'([^']*)',$/gm)].map(
    (match) => match[1]!,
  );
  return { rangeCount, startGaps: startGaps!, rangeLens: rangeLens!, codes: codes! };
}

describe('renderRangesModule', () => {
  const { source, encoded, validation } = renderRangesModule(ROWS, META, OPTS);

  it('emits a module whose encoded columns decode back to the input ranges', () => {
    // The real risk in a code generator is the TEMPLATE, not the algorithm —
    // a stray quote or an off-by-one in the string interpolation ships a file
    // that only fails when something imports it. So parse the rendered source
    // and run it through the runtime decoder.
    const table = decodeCMunTable(extractColumns(source));

    expect([...table.starts]).toEqual([1_000_000, 1_100_000, 2_000_000, 7_000_000]);
    expect([...table.ends]).toEqual([1_099_999, 1_199_999, 2_099_999, 7_299_999]);
    expect([...table.codes]).toEqual([3_550_308, 3_550_308, 3_304_557, 5_300_108]);
  });

  it('records the provenance the refresh runbook depends on', () => {
    expect(source).toContain(`dumpFile: '${META.dumpFile}'`);
    expect(source).toContain(`dumpSha256: '${META.dumpSha256}'`);
    expect(source).toContain(`exportedAt: '${META.exportedAt}'`);
    expect(source).toContain('codeCount: 3');
  });

  it('marks the file as generated and names the regeneration command', () => {
    expect(source).toContain('GENERATED by tools/cmun-table');
    expect(source).toContain('DO NOT EDIT');
    expect(source).toContain('pnpm --filter @delfrance/cmun-table vendor');
  });

  it('imports the type from the sibling codec rather than re-declaring it', () => {
    expect(source).toContain("import type { EncodedCMunTable } from './codec';");
  });

  it('reports the gap between the RJ and DF faixas', () => {
    expect(validation.gaps.count).toBe(2); // 1.2M–1.99M and 2.1M–6.99M
    expect(encoded.rangeCount).toBe(4);
  });

  it('emits only base36 characters and commas in the data columns', () => {
    const columns = extractColumns(source);
    for (const column of [columns.startGaps, columns.rangeLens, columns.codes]) {
      // Anything else would break the single-pass decoder — and a quote would
      // break the module outright.
      expect(column).toMatch(/^[0-9a-z,]*$/);
    }
  });

  it('propagates a validation failure instead of writing a bad table', () => {
    expect(() => renderRangesModule([{ ...ROWS[0]!, cMun: 'bogus' }], META, OPTS)).toThrow(/cMun/);
  });
});
